#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

# Board FRAM - Board Farm Remote Access Management - Client convenience wrapper
#
# Copyright (C) 2023-2024 Glider bv

set -e

CONFIG="$HOME/.framrc"
test -f "$CONFIG" || { echo Config file "$CONFIG" does not exist; exit 1; }

function usage()
{
	cat <<END
Board FRAM - Board Farm Remote Access Management

Usage:
    $(basename "$0") <command>
    $(basename "$0") <board> <command> ...

Generic commands are:

    help                           Show this usage information
    list                           List all available boards

Basic board-specific commands are:

    help                           Show full board usage information
    console                        Access the board console
    ls                             List the boot directory contents
    power [on|off|status*]         Control board power
    reset                          Reset board
    status                         Show board status
    upload <file> ...              Upload files to boot directory

Options marked with an asterisk are the default.

Use "fram <board> help" for more commands and board-specific usage information.
END
	exit 0
}

CMD=$(basename "$0")
if [ "$CMD" != "fram" ]; then
	BOARD=${CMD#*-}
	CMD=${CMD%%-*}
elif [ $# -ge 2 ]; then
	BOARD=$1
	shift
	CMD=$1
	shift
else
	case $1 in
	list)
		cut -d = -f 1 "$CONFIG"
		;;

	*)
		usage
		;;
	esac
	exit 0
fi

TARGET=$(sed -n -e "s/^$BOARD=//p" "$CONFIG")
test -z "$TARGET" && { echo "$BOARD" not found in "$CONFIG"; exit 1; }

case "${CMD}" in
console|shell)
	SSH_ARGS=-t
	;;

upload)
	rsync -zav "$@" "$TARGET:"
	exit 0
	;;
esac

ssh $SSH_ARGS "$TARGET" "$CMD" "$@"
