#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only

# Copyright (C) 2022-2023 Glider bv
# Copyright (C) 2022 Ideas on Board

mkdir -p -m 700 "${HOME}/.ssh"

for f in authorized_keys.d/*; do
	user=$(basename "${f}" .pub);
	user=${user%@*}
	printf "restrict,pty,command=\"%s/bin/fram-server %s\" " "${PWD}" "${user}"
	head -n 1 "${f}"
done > "${HOME}/.ssh/authorized_keys"

chmod 600 "${HOME}/.ssh/authorized_keys"
